import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:note_secret_search/shared/navigation/app_destination.dart';
import 'package:note_secret_search/features/search/application/semantic_quality_policy.dart';
import 'package:note_secret_search/features/search/application/search_fusion_service.dart';
import 'package:note_secret_search/features/search/application/search_providers.dart';
import 'package:note_secret_search/features/search/application/semantic_search_readiness_providers.dart';
import 'package:note_secret_search/features/search/domain/embedding_engine.dart';
import 'package:note_secret_search/features/search/domain/search_result_item.dart';
import 'package:note_secret_search/features/search/domain/semantic_search_result.dart';
import 'package:note_secret_search/features/search/presentation/search_result_explanation.dart';
import 'package:note_secret_search/features/search/presentation/search_status_summary.dart';
import 'package:note_secret_search/features/search/presentation/detail_search_hit_target.dart';

part 'search_page_page.dart';
part 'search_page_status.dart';
part 'search_page_observability.dart';
part 'search_page_result.dart';
