android.useAndroidX=true
android.enableJetifier=false
android.suppressUnsupportedCompileSdk=36,35
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC
kotlin.incremental=false
noteSecretSearch.javaVersion=17
noteSecretSearch.android.compileSdk=36
noteSecretSearch.android.targetSdk=34
noteSecretSearch.android.minSdk=24
noteSecretSearch.android.ndkVersion=28.2.13676358
